In [3]:
# Import dependencies
import pandas as pd

In [10]:
# Load csv to dataframe
df = pd.read_csv(r"C:\Users\cameu\Desktop\Python Pandas Learning\Datasets\countries of the world.csv")
df.head()

           Country                               Region
0     Afghanistan         ASIA (EX. NEAR EAST)
1         Albania   EASTERN EUROPE
2         Algeria   NORTHERN AFRICA
3  American Samoa   OCEANIA
4         Andorra   WESTERN EUROPE

In [13]:
# Load txt file to dataframe
df = pd.read_table(r'C:\Users\cameu\Desktop\Python Pandas Learning\Datasets\countries of the world.txt')
df.head()

           Country                               Region
0     Afghanistan         ASIA (EX. NEAR EAST)
1         Albania   EASTERN EUROPE
2         Algeria   NORTHERN AFRICA
3  American Samoa   OCEANIA
4         Andorra   WESTERN EUROPE

In [14]:
df = pd.read_json(r'C:\Users\cameu\Desktop\Python Pandas Learning\Datasets\json_sample.json')
df.head()

,12 Strong,A Fantastic Woman (Una Mujer Fantástica),All The Money In The World,Bilal: A New Breed Of Hero,Call Me By Your Name,Darkest Hour,Den Of Thieves,Ferdinand,Fifty Shades Freed,Film Stars Don'T Die In Liverpool,...,The 15:17 To Paris,The Commuter,The Disaster Artist,The Greatest Showman,The Insult (L'Insulte),The Post,The Shape Of Water,"Three Billboards Outside Ebbing, Missouri",Till The End Of The World,Winchester
0,"{'Genre': 'Action', 'Gross': '$453,173', 'IMDB...","{'popcornscore': 83, 'rating': 'R', 'tomatosco...","{'popcornscore': 71, 'rating': 'R', 'tomatosco...","{'popcornscore': 91, 'rating': 'PG13', 'tomato...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': 84, 'rating': 'PG13', 'tomato...","{'Genre': 'Action', 'Gross': '$491,898', 'IMDB...","{'popcornscore': 49, 'rating': 'PG', 'tomatosc...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 69, 'rating': 'R', 'tomatosco...",...,"{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 48, 'rating': 'PG13', 'tomato...","{'popcornscore': 89, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$627,248', 'I...","{'popcornscore': 86, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$463,228', 'I...","{'Genre': 'Adventure', 'Gross': '$448,287', 'I...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': -1, 'rating': 'NR', 'tomatosc...","{'Genre': 'Biography', 'Gross': '$696,786', 'I..."

In [15]:
df = pd.read_excel(r'C:\Users\cameu\Desktop\Python Pandas Learning\Datasets\world_population_excel_workbook.xlsx', sheet_name='Sheet1')
df.head()

   Rank CCA3         Country           Capital
0    36  AFG     Afghanistan             Kabul
1   138  ALB         Albania            Tirana
2    34  DZA         Algeria           Algiers
3   213  ASM  American Samoa         Pago Pago
4   203  AND         Andorra  Andorra la Vella