In [ ]:
# Import dependencies
import pandas as pd

In [6]:
# Load csv to dataframe
df = pd.read_csv('Datasets/countries of the world.csv')
df.head()

           Country                               Region
0     Afghanistan         ASIA (EX. NEAR EAST)
1         Albania   EASTERN EUROPE
2         Algeria   NORTHERN AFRICA
3  American Samoa   OCEANIA
4         Andorra   WESTERN EUROPE

In [ ]:
# Load txt file to dataframe
df = pd.read_table('Datasets/countries of the world.txt')
df.head()

           Country                               Region
0     Afghanistan         ASIA (EX. NEAR EAST)
1         Albania   EASTERN EUROPE
2         Algeria   NORTHERN AFRICA
3  American Samoa   OCEANIA
4         Andorra   WESTERN EUROPE